// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentDocumentStores;

#nullable disable

namespace AdmissionsPortalWebApp.Migrations.StudentDocumentDb
{
    [DbContext(typeof(StudentDocumentDbContext))]
    partial class StudentDocumentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentDocuments.PersonPassport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("WhenChanged")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenCreated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PersonPassport");
                });

            modelBuilder.Entity("StudentDocuments.PersonResidencePermit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("WhenChanged")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenCreated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PersonResidencePermit");
                });

            modelBuilder.Entity("StudentDocuments.PersonVisa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("WhenChanged")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenCreated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PersonVisa");
                });

            modelBuilder.Entity("StudentDocuments.PersonPassport", b =>
                {
                    b.OwnsOne("StudentDocuments.PersonInfo", "Manager", b1 =>
                        {
                            b1.Property<int>("PersonPassportId")
                                .HasColumnType("int");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("PersonPassportId");

                            b1.ToTable("PersonPassport");

                            b1.WithOwner()
                                .HasForeignKey("PersonPassportId");
                        });

                    b.OwnsOne("StudentDocuments.PersonInfo", "Owner", b1 =>
                        {
                            b1.Property<int>("PersonPassportId")
                                .HasColumnType("int");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("PersonPassportId");

                            b1.ToTable("PersonPassport");

                            b1.WithOwner()
                                .HasForeignKey("PersonPassportId");
                        });

                    b.OwnsOne("StudentDocuments.PersonPassportInfo", "Passport", b1 =>
                        {
                            b1.Property<int>("PersonPassportId")
                                .HasColumnType("int");

                            b1.Property<string>("Authority")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .IsUnicode(false)
                                .HasColumnType("varchar(10)");

                            b1.Property<DateTime>("DateOfBirth")
                                .HasColumnType("date");

                            b1.Property<DateTime>("DateOfExpiration")
                                .HasColumnType("date");

                            b1.Property<DateTime>("DateOfIssue")
                                .HasColumnType("date");

                            b1.Property<string>("GivenName")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("Nationality")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("PassportNumber")
                                .IsRequired()
                                .HasColumnType("char(9)");

                            b1.Property<string>("PlaceOfBirth")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("Sex")
                                .IsRequired()
                                .HasMaxLength(10)
                                .IsUnicode(false)
                                .HasColumnType("varchar(10)");

                            b1.Property<string>("Surname")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(10)
                                .IsUnicode(false)
                                .HasColumnType("varchar(10)");

                            b1.HasKey("PersonPassportId");

                            b1.ToTable("PersonPassport");

                            b1.WithOwner()
                                .HasForeignKey("PersonPassportId");
                        });

                    b.Navigation("Manager")
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Passport")
                        .IsRequired();
                });

            modelBuilder.Entity("StudentDocuments.PersonResidencePermit", b =>
                {
                    b.OwnsOne("StudentDocuments.PersonInfo", "Manager", b1 =>
                        {
                            b1.Property<int>("PersonResidencePermitId")
                                .HasColumnType("int");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("PersonResidencePermitId");

                            b1.ToTable("PersonResidencePermit");

                            b1.WithOwner()
                                .HasForeignKey("PersonResidencePermitId");
                        });

                    b.OwnsOne("StudentDocuments.PersonInfo", "Owner", b1 =>
                        {
                            b1.Property<int>("PersonResidencePermitId")
                                .HasColumnType("int");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("PersonResidencePermitId");

                            b1.ToTable("PersonResidencePermit");

                            b1.WithOwner()
                                .HasForeignKey("PersonResidencePermitId");
                        });

                    b.OwnsOne("StudentDocuments.ResidencePermitInfo", "ResidencePermit", b1 =>
                        {
                            b1.Property<int>("PersonResidencePermitId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("DateOfBirth")
                                .HasColumnType("date");

                            b1.Property<DateTime>("DateOfIssue")
                                .HasColumnType("date");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(9)
                                .IsUnicode(false)
                                .HasColumnType("varchar(9)");

                            b1.Property<string>("Observations")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("PassportNumber")
                                .IsRequired()
                                .HasColumnType("char(9)");

                            b1.Property<string>("PlaceOfIssue")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("PurposeForResidence")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("Sex")
                                .IsRequired()
                                .HasMaxLength(10)
                                .IsUnicode(false)
                                .HasColumnType("varchar(10)");

                            b1.Property<DateTime>("ValidForResidenceUntil")
                                .HasColumnType("date");

                            b1.HasKey("PersonResidencePermitId");

                            b1.ToTable("PersonResidencePermit");

                            b1.WithOwner()
                                .HasForeignKey("PersonResidencePermitId");
                        });

                    b.Navigation("Manager")
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("ResidencePermit")
                        .IsRequired();
                });

            modelBuilder.Entity("StudentDocuments.PersonVisa", b =>
                {
                    b.OwnsOne("StudentDocuments.PersonInfo", "Manager", b1 =>
                        {
                            b1.Property<int>("PersonVisaId")
                                .HasColumnType("int");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("PersonVisaId");

                            b1.ToTable("PersonVisa");

                            b1.WithOwner()
                                .HasForeignKey("PersonVisaId");
                        });

                    b.OwnsOne("StudentDocuments.PersonInfo", "Owner", b1 =>
                        {
                            b1.Property<int>("PersonVisaId")
                                .HasColumnType("int");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("PersonVisaId");

                            b1.ToTable("PersonVisa");

                            b1.WithOwner()
                                .HasForeignKey("PersonVisaId");
                        });

                    b.OwnsOne("StudentDocuments.PersonVisaInfo", "Visa", b1 =>
                        {
                            b1.Property<int>("PersonVisaId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("BirthDate")
                                .HasColumnType("date");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasMaxLength(10)
                                .IsUnicode(false)
                                .HasColumnType("varchar(10)");

                            b1.Property<int>("DurationOfEachStay")
                                .HasColumnType("int");

                            b1.Property<DateTime>("EnterBefore")
                                .HasColumnType("date");

                            b1.Property<int>("Entries")
                                .HasColumnType("int");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)");

                            b1.Property<DateTime>("IssueDate")
                                .HasColumnType("date");

                            b1.Property<string>("IssuedAt")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("PassportNumber")
                                .IsRequired()
                                .HasColumnType("char(9)");

                            b1.Property<string>("Remarks")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("VisaNumber")
                                .IsRequired()
                                .HasMaxLength(32)
                                .IsUnicode(false)
                                .HasColumnType("varchar(32)");

                            b1.HasKey("PersonVisaId");

                            b1.ToTable("PersonVisa");

                            b1.WithOwner()
                                .HasForeignKey("PersonVisaId");
                        });

                    b.Navigation("Manager")
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Visa")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
